--liquibase formatted sql

--changeset ekualiti:EKC_1351_Award_Report_Tracking

DROP TABLE IF EXISTS `SEQ_AWARD_REPORT_TRACKING_ID`;
CREATE TABLE `SEQ_AWARD_REPORT_TRACKING_ID` (
  `id` bigint(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


ALTER TABLE `award_report_tracking`
  ADD COLUMN `AWARD_REPORT_TRACKING_ID` bigint(19) NOT NULL AUTO_INCREMENT FIRST,
  ADD PRIMARY KEY (`AWARD_REPORT_TRACKING_ID`);

DELETE from `award_report_tracking` where `AWARD_REPORT_TERM_ID` is null;

INSERT INTO `SEQ_AWARD_REPORT_TRACKING_ID` SELECT `AWARD_REPORT_TRACKING_ID` FROM `award_report_tracking`;

