--liquibase formatted sql

--changeset ekualiti:90560752-add-active-ind-iacuc-documents

ALTER TABLE IACUC_ALT_SEARCH_DB ADD COLUMN ACTIVE_FLAG varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y';

ALTER TABLE IACUC_LOCATION_NAME ADD COLUMN ACTIVE_FLAG varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y';

ALTER TABLE IACUC_LOCATION_TYPE ADD COLUMN ACTIVE_FLAG varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y';

ALTER TABLE IACUC_PERSON_TRAINING ADD COLUMN ACTIVE_FLAG varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y';

ALTER TABLE IACUC_PROCEDURES ADD COLUMN ACTIVE_FLAG varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y';

ALTER TABLE IACUC_PROTOCOL_PROJECT_TYPE ADD COLUMN ACTIVE_FLAG varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y';

ALTER TABLE IACUC_SPECIES ADD COLUMN ACTIVE_FLAG varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y';

ALTER TABLE IACUC_SPECIES_COUNT_TYPE ADD COLUMN ACTIVE_FLAG varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y';